
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getClients() : Promise<Result<Client[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clients") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addClient(client: CreateClientDto) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_client", { client }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateClient(client: UpdateClientDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_client", { client }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClientSessions(clientId: number) : Promise<Result<Session[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_client_sessions", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSession(session: CreateSessionDto) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveImage(clientId: number, clientFirstname: string, sessionNo: number, imageType: string, base64Image: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_image", { clientId, clientFirstname, sessionNo, imageType, base64Image }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readImageBase64(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_image_base64", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNextSessionNumber(clientId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_next_session_number", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSessionCrop(sessionId: number, imageType: string, cropData: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_session_crop", { sessionId, imageType, cropData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Client = { id: number; firstname: string; lastname: string; dob: string; sex: string; registration_date: string }
export type CreateClientDto = { firstname: string; lastname: string; dob: string; sex: string }
export type CreateSessionDto = { client_id: number; height: number | null; weight: number | null; anterior: string | null; posterior: string | null; right_lateral: string | null; left_lateral: string | null; notes: string | null; anterior_crop: string | null; posterior_crop: string | null; right_lateral_crop: string | null; left_lateral_crop: string | null }
export type Session = { id: number; client_id: number; datetime: string; session_number: number; height: number | null; weight: number | null; anterior: string | null; posterior: string | null; right_lateral: string | null; left_lateral: string | null; notes: string | null; anterior_crop: string | null; posterior_crop: string | null; right_lateral_crop: string | null; left_lateral_crop: string | null }
export type UpdateClientDto = { id: number; firstname: string; lastname: string; dob: string; sex: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
